
const mongoose=require("mongoose")

const vlogeraddingSchema=new mongoose.Schema({
    place:{
        require:true,
        type:String
    },
    title:{
        require:true,
        type:String
    },
    titleimg:{
        require:true,
        type:String
    },
    date:{
        require:true,
        type:String
    },
    head1:{
        require:true,
        type:String
    },
    img1:{
        require:true,
        type:String
    },
    dis1:{
        require:true,
        type:String
    },
    head2:{
        require:true,
        type:String
    },
    img2:{
        require:true,
        type:String
    },
    dis2:{
        require:true,
        type:String
    },
    head3:{
        require:true,
        type:String
    },
    img3:{
        require:true,
        type:String
    },
    dis3:{
        require:true,
        type:String
    },
    head4:{
        require:true,
        type:String
    },
    img4:{
        require:true,
        type:String
    },
    dis4:{
        require:true,
        type:String
    },
    ur1:{
        require:true,
        type:String
    },
    url2:{
        require:true,
        type:String
    },
    url3:{
        require:true,
        type:String
    },
    url4:{
        require:true,
        type:String
    },
    vName:{
        require:true,
        type:String 
    },
    userId:{
        type:String,
        require:true
    }
})

const vlogeradds=mongoose.model("vlogeradds",vlogeraddingSchema)
module.exports=vlogeradds